### ISSUE TITLE
sendMessage not working

### ISSUE THREAD

**Issue by qadirsuh** [smooch/smooch-core-js#128]
I am trying to send message to user via **Bot**. but sendMessage not working.
Its throwing error as **400 Bad Request**.

here is my error logs

```
Catch called { Error: Bad Request
    at handleStatus (/Users/qadir/Desktop/Development/nodeJS/qJamesBot/node_modules/smooch-core/lib/utils/http.js:45:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  response: 
   Body {
     url: 'https://api.smooch.io/v1/appUsers/d5431e57cf5910754b2c678b/messages',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { _headers: [Object] },
     ok: false,
     body: 
      PassThrough {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: false,
     size: 0,
     timeout: 0,
     _raw: [],
     _abort: false } }
```

Here is SmoochMessageFormat class in javascript.
please check my sendMessage() function whats wrong in it?

```
'use strict';

const FirebaseHelper = require('../libs/FirebaseHelper.js');

const JwtGeneratorForSmoochJamesAppLogin = require('../libs/JwtGeneratorForSmoochJamesAppLogin.js');
var jwtGeneratorForSmoochJamesAppLogin = new JwtGeneratorForSmoochJamesAppLogin();

const SmoochCore = require('smooch-core');
var smooch = null;

class SmoochMessageFormat {

    constructor(smoochBot, smoochBotReq, callBack) {
        // create smooch Core depending on useSmoochProd object

        this.smoochBotReq = smoochBotReq;
        this.smoochBot = smoochBot;

        var firebaseHelper = new FirebaseHelper(smoochBot.userId, function () {

            //Check for firebase env and select the appropriate food list
            var useSmoochProdUri = firebaseHelper.getAppConstantsObj().use_smooch_prod
            firebaseHelper.getData(useSmoochProdUri, function (useSmoochProd) {

                console.log("useSmoochProd", useSmoochProd);
                smooch = new SmoochCore({jwt: jwtGeneratorForSmoochJamesAppLogin.getJwtSmoochCore(useSmoochProd)});
                callBack();
            })

        })
    }


    sendMessage(data) {

        let appId = this.smoochBotReq.app._id;
        let appUser = this.smoochBotReq.appUser._id;
        let userId = this.smoochBot.userId;

        console.log("appId", appId);
        console.log("appUser", appUser);

        let datas = {
            appId: appId,
            appUser: appUser,
            message: {
                role: 'appUser',
                type: 'text',
                text: 'Hello! Testing',
                metadata: {
                    lang: 'en-ca',
                    items: 3
                },
                actions: [
                    {
                        text: 'More info',
                        type: 'link',
                        uri: 'https://smooch.io/',
                        metadata: {
                            buttonIntent: 'moreInfo'
                        }
                    }
                ]
            }
        }

        // console.log("datas", datas);
        // console.log("Smooch", smooch);
        // console.log("appUsers", smooch.appUsers);

        smooch.appUsers.sendMessage(userId, datas).then((res) => {
            // async code
            console.log("then called", res);
        }).catch((err) => {
            console.log("Catch called", err);
        })
    }

}

module.exports = SmoochMessageFormat;
```

**Comment by mspensieri** [comment]
I see two obvious issues with the code snippet above

1. In your data object you are passing `appUser` instead of `userId` [as documented](https://docs.smooch.io/rest/?javascript#get-messages)
2. You are passing two arguments to the `sendMessage` function instead of one

Try this?

```javascript
let datas = {
    appId: appId,
    userId: appUser,
    message: {
        role: 'appUser',
        type: 'text',
        text: 'Hello! Testing',
        metadata: {
            lang: 'en-ca',
            items: 3
        },
        actions: [
            {
                text: 'More info',
                type: 'link',
                uri: 'https://smooch.io/',
                metadata: {
                    buttonIntent: 'moreInfo'
                }
            }
        ]
    }
}

smooch.appUsers.sendMessage(datas)
```

**Comment by qadirsuh** [comment]
Actually I was following carousel doc. is sendMessage work differently over there?
[](https://docs.smooch.io/rest/?javascript#carousel)

**Comment by mspensieri** [comment]
Nope it should be the same, looks like a mistake in the carousel example

**Comment by qadirsuh** [comment]
This worked for me. thanks for pointing out your own mistake. :)
Please correct carousel docs
